name: sonicwallvpn/

on:
  push:
    paths:
    - 'sonicwallvpn-login/**'
    branches:
      - main
      
  workflow_dispatch:

jobs:
  push_to_registry:
  
    name: push image to github registry
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2

      - name: authenticate to gh container registry 
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build & push image
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./sonicwallvpn-login
          push: true 
          tags: |
            ghcr.io/${{ github.repository }}/sonicwallvpn-login:latest
